language: python
python: "3.7"
jobs:
  include:
  - name: "MacOS",
    os: osx
  - name: "Windows",
    os: windows
  - name: "Ubuntu",
    dist: focal
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install pyinstaller
script:
  - pyinstaller build.spec